"""Pares Level Sub-Area (exactamente 2 lunas en alcance).

Fuente operativa de load_sub_area_levels / rebuild_sub_area_bingo.
No vive en goal_lists.json (no es pool lista[] de bingo_groups).
"""

from __future__ import annotations

SUB_AREA_LEVELS: list[dict] = [
    {
        "kingdom": "cap",
        "id_list": 1,
        "level": "Poison Tide",
        "moons": [6, 7],
        "names": ["Skimming the Poison Tide", "Slipping Through the Poison Tide"],
    },
    {
        "kingdom": "cap",
        "id_list": 2,
        "level": "Push-Block Peril",
        "moons": [8, 9],
        "names": ["Push-Block Peril", "Hidden Among the Push-Blocks"],
    },
    {
        "kingdom": "cap",
        "id_list": 3,
        "level": "Frog Pond",
        "moons": [10, 11],
        "names": ["Searching the Frog Pond", "Secrets of the Frog Pond"],
    },
    {
        "kingdom": "cascade",
        "id_list": 4,
        "level": "Dinosaur Nest",
        "moons": [12, 13],
        "names": ["Dinosaur Nest: Big Cleanup!", "Dinosaur Nest: Running Wild!"],
    },
    {
        "kingdom": "cascade",
        "id_list": 5,
        "level": "Chain Chomp Cave",
        "moons": [14, 15],
        "names": ["Nice Shot with the Chain Chomp!", "Very Nice Shot with the Chain Chomp!"],
    },
    {
        "kingdom": "cascade",
        "id_list": 6,
        "level": "Chasm Lifts",
        "moons": [16, 17],
        "names": ["Past the Chasm Lifts", "Hidden Chasm Passage"],
    },
    {
        "kingdom": "sand",
        "id_list": 7,
        "level": "Invisible Maze",
        "moons": [54, 55],
        "names": ["The Invisible Maze", "Skull Sign in the Transparent Maze"],
    },
    {
        "kingdom": "sand",
        "id_list": 8,
        "level": "Bullet Bill Maze",
        "moons": [56, 57],
        "names": ["The Bullet Bill Maze: Break Through!", "The Bullet Bill Maze: Side Path"],
    },
    {
        "kingdom": "sand",
        "id_list": 9,
        "level": "Jaxi Driving",
        "moons": [58, 59],
        "names": ["Jaxi Driver", "Jaxi Stunt Driving"],
    },
    {
        "kingdom": "sand",
        "id_list": 10,
        "level": "Strange Neighborhood",
        "moons": [60, 61],
        "names": ["Strange Neighborhood", "Above a Strange Neighborhood"],
    },
    {
        "kingdom": "lake",
        "id_list": 11,
        "level": "Zipper Chasm",
        "moons": [22, 23],
        "names": ["Unzip the Chasm", "Super-Secret Zipper"],
    },
    {
        "kingdom": "lake",
        "id_list": 12,
        "level": "Climbing Course",
        "moons": [24, 25],
        "names": ["Jump, Grab, Cling, and Climb", "Jump, Grab, and Climb Some More"],
    },
    {
        "kingdom": "wooded",
        "id_list": 13,
        "level": "Flooding Pipeway",
        "moons": [39, 40],
        "names": ["Flooding Pipeway", "Flooding Pipeway Ceiling Secret"],
    },
    {
        "kingdom": "wooded",
        "id_list": 14,
        "level": "Foggy Room",
        "moons": [41, 42],
        "names": ["Wandering in the Fog", "Nut Hidden in the Fog"],
    },
    {
        "kingdom": "wooded",
        "id_list": 15,
        "level": "Flower Road Run",
        "moons": [43, 44],
        "names": ["Flower Road Run", "Flower Road Reach"],
    },
    {
        "kingdom": "wooded",
        "id_list": 16,
        "level": "Elevator Shaft",
        "moons": [45, 46],
        "names": ["Elevator Escalation", "Elevator Blind Spot"],
    },
    {
        "kingdom": "wooded",
        "id_list": 17,
        "level": "Cloud Walking",
        "moons": [47, 48],
        "names": ["Walking on Clouds", "Above the Clouds"],
    },
    {
        "kingdom": "metro",
        "id_list": 18,
        "level": "Crowded Room",
        "moons": [37, 38],
        "names": ["Pushing Through the Crowd", "High Over the Crowd"],
    },
    {
        "kingdom": "metro",
        "id_list": 19,
        "level": "Wire Neighborhood",
        "moons": [39, 40],
        "names": ["Rewiring the Neighborhood", "Off the Beaten Wire"],
    },
    {
        "kingdom": "metro",
        "id_list": 20,
        "level": "Under Siege",
        "moons": [41, 42],
        "names": ["Moon Shards Under Siege", "Sharpshooting Under Siege"],
    },
    {
        "kingdom": "metro",
        "id_list": 21,
        "level": "Rotating Maze",
        "moons": [43, 44],
        "names": ["Inside the Rotating Maze", "Outside the Rotating Maze"],
    },
    {
        "kingdom": "metro",
        "id_list": 22,
        "level": "High-Rise Building",
        "moons": [45, 46],
        "names": ["Hanging from a High-Rise", "Vaulting Up a High-Rise"],
    },
    {
        "kingdom": "metro",
        "id_list": 23,
        "level": "Bullet Billding",
        "moons": [47, 48],
        "names": ["Bullet Billding", "One Man's Trash..."],
    },
    {
        "kingdom": "metro",
        "id_list": 24,
        "level": "T-Rex Chase",
        "moons": [49, 50],
        "names": ["Motor Scooter: Escape!", "Big Jump: Escape!"],
    },
    {
        "kingdom": "snow",
        "id_list": 25,
        "level": "Cold Water Dash",
        "moons": [24, 25],
        "names": ["Dashing Over Cold Water!", "Dashing Above and Beyond!"],
    },
    {
        "kingdom": "snow",
        "id_list": 26,
        "level": "Freezing Water Swim",
        "moons": [26, 27],
        "names": ["Jump 'n' Swim in the Freezing Water", "Freezing Water Near the Ceiling"],
    },
    {
        "kingdom": "snow",
        "id_list": 27,
        "level": "Cold Room",
        "moons": [29, 30],
        "names": ["Moon Shards in the Cold Room", "Slip Behind the Ice"],
    },
    {
        "kingdom": "snow",
        "id_list": 28,
        "level": "Cloud Spinning",
        "moons": [31, 32],
        "names": ["Spinning Above the Clouds", "High-Altitude Spinning"],
    },
    {
        "kingdom": "seaside",
        "id_list": 29,
        "level": "Cloud Sea",
        "moons": [43, 44],
        "names": ["Wading in the Cloud Sea", "Sunken Treasure in the Cloud Sea"],
    },
    {
        "kingdom": "seaside",
        "id_list": 30,
        "level": "Narrow Valley",
        "moons": [45, 46],
        "names": ["Fly Through the Narrow Valley", "Treasure Chest in the Narrow Valley"],
    },
    {
        "kingdom": "seaside",
        "id_list": 31,
        "level": "Sinking Island",
        "moons": [47, 48],
        "names": ["Hurry and Stretch", "Stretch on the Side Path"],
    },
    {
        "kingdom": "luncheon",
        "id_list": 32,
        "level": "Simmering Room",
        "moons": [27, 28],
        "names": ["A Strong Simmer", "An Extreme Simmer"],
    },
    {
        "kingdom": "luncheon",
        "id_list": 33,
        "level": "Magma Swamp",
        "moons": [37, 38],
        "names": ["Magma Swamp: Floating and Sinking", "Corner of the Magma Swamp"],
    },
    {
        "kingdom": "luncheon",
        "id_list": 34,
        "level": "Magma Crossing",
        "moons": [39, 40],
        "names": ["Magma Narrow Path", "Crossing to the Magma"],
    },
    {
        "kingdom": "luncheon",
        "id_list": 35,
        "level": "Fork Flickin'",
        "moons": [41, 42],
        "names": ["Fork Flickin' to the Summit", "Fork Flickin' Detour"],
    },
    {
        "kingdom": "luncheon",
        "id_list": 36,
        "level": "Cheese Rocks Room",
        "moons": [43, 44],
        "names": ["Excavate 'n' Search the Cheese Rocks", "Climb the Cheese Rocks"],
    },
    {
        "kingdom": "luncheon",
        "id_list": 37,
        "level": "Spinning Athletics",
        "moons": [45, 46],
        "names": ["Spinning Athletics End Goal", "Taking Notes: Spinning Athletics"],
    },
    {
        "kingdom": "ruined",
        "id_list": 38,
        "level": "Roulette Tower",
        "moons": [3, 4],
        "names": ["Roulette Tower: Climbed", "Roulette Tower: Stopped"],
    },
    {
        "kingdom": "bowser",
        "id_list": 39,
        "level": "Folding Screen",
        "moons": [31, 32],
        "names": ["Scene of Crossing the Poison Swamp", "Taking Notes: In the Folding Screen"],
    },
    {
        "kingdom": "bowser",
        "id_list": 40,
        "level": "Spinning Tower",
        "moons": [33, 34],
        "names": ["On Top of the Spinning Tower", "Down and Up the Spinning Tower"],
    },
    {
        "kingdom": "bowser",
        "id_list": 41,
        "level": "Jizo Adventure",
        "moons": [35, 36],
        "names": ["Jizo's Big Adventure", "Jizo and the Hidden Room"],
    },
    {
        "kingdom": "bowser",
        "id_list": 42,
        "level": "Cloud Dashing",
        "moons": [37, 38],
        "names": ["Dashing Above the Clouds", "Dashing Through the Clouds"],
    },
]
